---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.0
_src_path: gh:radio-aktywne/template-generic
accountname: radio-aktywne
description: 'GitHub config :octocat:'
docs: false
projectname: .github
releases: false
reponame: .github
repourl: https://github.com/radio-aktywne/.github
