# Enable all rules by default
default: true

# Disable checking line length of code blocks
MD013:
  code_blocks: false

# Allow multiple top level headers
MD025: false

# Allow inline HTML
MD033: false

# Allow not using top level header
MD041: false
